version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/Email" #Email.csproj
      - "/src/Email.Models" #Email.Models.csproj
      - "/tests" #EmailTests.csproj
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "nuget"
      - "dependencies"
